In [2]:
import torch

l = []
for i in range(5):
    l.append(torch.randn(2,3))

In [17]:
def f(a):
    return a

In [21]:
arr = [torch.randn(2,3,4), torch.randn(2,3,4)]
print(torch.cat(arr, dim=0).shape)
t = torch.randn(2,3,4)
print(torch.cat((t, t), dim=0).shape)

torch.Size([4, 3, 4])
torch.Size([4, 3, 4])


In [18]:
a = torch.randn(3,4,5)
print(a)
print(a[...,2])
print(f(a[...,2]))
print(a[...,2].shape)

tensor([[[-0.4251,  0.0034, -0.5901,  0.7571, -0.7382],
         [ 0.7717, -0.6575,  1.7376, -1.5706, -1.1512],
         [ 0.2641, -1.3054, -0.3963,  0.7392, -0.2867],
         [-0.4492,  0.6661,  0.7378, -1.3840, -0.7549]],

        [[ 0.7605,  0.9529, -1.7958,  0.2337,  0.0977],
         [-1.0595, -0.2311,  0.5171,  0.2542, -0.4477],
         [-0.4541,  0.9002,  0.1228,  0.3227,  2.6733],
         [ 0.4577,  1.1491, -0.0227, -0.3951,  0.2788]],

        [[ 0.7942,  0.0143,  0.3223, -0.1098, -0.1269],
         [-1.3521,  0.6681, -1.2112, -0.9647, -0.3525],
         [-0.5290,  0.0781,  0.3802, -0.3336, -1.4807],
         [ 0.4427, -1.2064,  0.5577, -2.3650,  0.3042]]])
tensor([[-0.5901,  1.7376, -0.3963,  0.7378],
        [-1.7958,  0.5171,  0.1228, -0.0227],
        [ 0.3223, -1.2112,  0.3802,  0.5577]])
tensor([[-0.5901,  1.7376, -0.3963,  0.7378],
        [-1.7958,  0.5171,  0.1228, -0.0227],
        [ 0.3223, -1.2112,  0.3802,  0.5577]])
torch.Size([3, 4])


In [98]:
ts = torch.randn(3,4,5)
res, id = torch.max(ts, dim = 0)
print(res.shape)
res, id = torch.max(ts, dim = 0)
print(res == ts)

torch.Size([4, 5])
tensor([[[False, False,  True, False, False],
         [False,  True, False, False, False],
         [False,  True, False, False, False],
         [ True, False,  True, False, False]],

        [[False,  True, False, False,  True],
         [ True, False,  True,  True, False],
         [False, False,  True, False,  True],
         [False,  True, False, False,  True]],

        [[ True, False, False,  True, False],
         [False, False, False, False,  True],
         [ True, False, False,  True, False],
         [False, False, False,  True, False]]])


In [55]:
a = torch.randn(2,3,4,1)
b = torch.randn(2,3,4)

print(a*b)

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 2

In [52]:
import numpy as np
a = np.array([0,1])
b = a.copy()
b[0] = 3
print(a)

[0 1]


In [67]:
a = torch.randn(2,3,4,5)
print(torch.flatten(a, end_dim = -2).shape)
print(a[...,2].shape)

torch.Size([24, 5])
torch.Size([2, 3, 4])


In [94]:
import torch.nn as nn
loss = nn.MSELoss(reduction="mean")
input = torch.randn(10,30,70,80,5, requires_grad=True)
target = torch.randn(10,30,70,80,5)


output = loss(input, target)
print(output)
output = loss(input.reshape(10,-1), target.reshape(10,-1))
print(output)


tensor(2.0014, grad_fn=<MseLossBackward0>)
tensor(2.0014, grad_fn=<MseLossBackward0>)


In [95]:
a=[[0.9, 0.45, 0.4, 0.35],[0.4, 0.8, 0.3, 0.25],[0.5, 0.45, 0.9, 0.35],[0.2, 0.18, 0.8, 0.1],[0.6, 0.45, 0.4, 0.9]]
b=[0,1,2,3,3]
[i[j] for i,j in zip(a,b)]

[0.9, 0.8, 0.9, 0.1, 0.9]

In [115]:
a = torch.randn(5,4,5,6)
b = torch.randn(5,1,1,6)

print(a == b)

tensor([[[[False, False, False, False, False, False],
          [False, False, False, False, False, False],
          [False, False, False, False, False, False],
          [False, False, False, False, False, False],
          [False, False, False, False, False, False]],

         [[False, False, False, False, False, False],
          [False, False, False, False, False, False],
          [False, False, False, False, False, False],
          [False, False, False, False, False, False],
          [False, False, False, False, False, False]],

         [[False, False, False, False, False, False],
          [False, False, False, False, False, False],
          [False, False, False, False, False, False],
          [False, False, False, False, False, False],
          [False, False, False, False, False, False]],

         [[False, False, False, False, False, False],
          [False, False, False, False, False, False],
          [False, False, False, False, False, False],
          [False, Fals

In [143]:
a = torch.Tensor([1, 2, 3, 4])
b = a[0:3]
b = 6
print(a)

tensor([1., 2., 3., 4.])


In [142]:
a = np.array([1, 2, 3, 4])
b = a + 1
b[1] += 1
print(a)

[1 2 3 4]


In [189]:
a = torch.Tensor([1, 2, 3, 4])
print(a.shape)
print(a[..., : 3])

torch.Size([4])
tensor([1., 2., 3.])


In [159]:
a = torch.randn(2, 2,5)
a[1, 1, :] = torch.Tensor([1,1,1,1,1])

print(a.shape)

torch.Size([2, 2, 5])


In [191]:
a = torch.tensor([2.], requires_grad=True)
c = 2*a*a*a
d = c.clone()
d.backward()
print(a.grad)


tensor([24.])


In [192]:
a = torch.tensor([2.], requires_grad=True)
c = 2*a*a*a
c.backward()
print(a.grad)

tensor([24.])


In [211]:
a = torch.tensor([2.], requires_grad=True)
b = a*a*2
with torch.no_grad():
    a = a*2
b.backward()
print(a.grad)

None


In [18]:
a = torch.randn(2,2,5)
a.unsqueeze(4)
print(a.shape)

torch.Size([2, 2, 5])


In [26]:
a = torch.tensor(3.0424e-100)
b = torch.tensor(3.0424e+100)
print(a*a)

tensor(0.)
