In [6]:
import torch

l = []
for i in range(5):
    l.append(torch.randn(2,3))

In [17]:
def f(a):
    return a

In [18]:
a = torch.randn(3,4,5)
print(a)
print(a[...,2])
print(f(a[...,2]))
print(a[...,2].shape)

tensor([[[-0.4251,  0.0034, -0.5901,  0.7571, -0.7382],
         [ 0.7717, -0.6575,  1.7376, -1.5706, -1.1512],
         [ 0.2641, -1.3054, -0.3963,  0.7392, -0.2867],
         [-0.4492,  0.6661,  0.7378, -1.3840, -0.7549]],

        [[ 0.7605,  0.9529, -1.7958,  0.2337,  0.0977],
         [-1.0595, -0.2311,  0.5171,  0.2542, -0.4477],
         [-0.4541,  0.9002,  0.1228,  0.3227,  2.6733],
         [ 0.4577,  1.1491, -0.0227, -0.3951,  0.2788]],

        [[ 0.7942,  0.0143,  0.3223, -0.1098, -0.1269],
         [-1.3521,  0.6681, -1.2112, -0.9647, -0.3525],
         [-0.5290,  0.0781,  0.3802, -0.3336, -1.4807],
         [ 0.4427, -1.2064,  0.5577, -2.3650,  0.3042]]])
tensor([[-0.5901,  1.7376, -0.3963,  0.7378],
        [-1.7958,  0.5171,  0.1228, -0.0227],
        [ 0.3223, -1.2112,  0.3802,  0.5577]])
tensor([[-0.5901,  1.7376, -0.3963,  0.7378],
        [-1.7958,  0.5171,  0.1228, -0.0227],
        [ 0.3223, -1.2112,  0.3802,  0.5577]])
torch.Size([3, 4])
